import type { CuratedDesign, MerchProduct } from './types';

export const curatedDesigns: CuratedDesign[] = [
  {
    id: 'design-pet-pop',
    title: 'Sunday Sidekick',
    description: 'A cheerful illustrated companion for everyday rooms.',
    collection: 'Pets',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-pet-pop',
      version: 'fixture-v1',
      url: '/landing/transformations/pet-cartoon.webp',
      alt: 'Colorful illustrated French bulldog portrait',
      width: 1200,
      height: 1200,
      mimeType: 'image/webp',
      hasTransparency: false,
    },
  },
  {
    id: 'design-family-oil',
    title: 'Golden Hour',
    description: 'Painterly warmth made for a thoughtful family keepsake.',
    collection: 'Portraits',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-family-oil',
      version: 'fixture-v1',
      url: '/landing/transformations/family-oil-painting.webp',
      alt: 'Family portrait rendered as an oil painting',
      width: 1200,
      height: 1200,
      mimeType: 'image/webp',
      hasTransparency: false,
    },
  },
  {
    id: 'design-travel-watercolor',
    title: 'Coastal Air',
    description: 'Soft watercolor color for a favorite trip or place.',
    collection: 'Travel',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-travel-watercolor',
      version: 'fixture-v1',
      url: '/landing/transformations/travel-watercolor.webp',
      alt: 'Travel landscape in a watercolor style',
      width: 1200,
      height: 1200,
      mimeType: 'image/webp',
      hasTransparency: false,
    },
  },
  {
    id: 'design-pet-photo',
    title: 'Quiet Company',
    description: 'A clean photographic favorite for understated gifts.',
    collection: 'Pets',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-pet-photo',
      version: 'fixture-v1',
      url: '/landing/transformations/pet-original.webp',
      alt: 'French bulldog portrait',
      width: 1200,
      height: 1200,
      mimeType: 'image/webp',
      hasTransparency: false,
    },
  },
  {
    id: 'design-travel-photo',
    title: 'Postcard Study',
    description: 'A crisp travel memory with an editorial feel.',
    collection: 'Travel',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-travel-photo',
      version: 'fixture-v1',
      url: '/landing/transformations/travel-original.webp',
      alt: 'Original travel landscape photograph',
      width: 1200,
      height: 1200,
      mimeType: 'image/webp',
      hasTransparency: false,
    },
  },
  {
    id: 'design-boo-crew',
    title: 'Boo Crew',
    description:
      'A charming collegiate trio of friendly ghosts and glowing jack-o-lanterns celebrating spooky season.',
    collection: 'Halloween',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-boo-crew',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/boo-crew.webp',
      productionUrl: '/designs/fall-2026/boo-crew.png',
      alt: 'Boo Crew retro collegiate Halloween ghosts and jack-o-lantern design',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-here-for-the-boos',
    title: 'Here for the Boos',
    description:
      'Playful speakeasy spirits cocktail artwork featuring a friendly ghost stirring up bubbly potion fun.',
    collection: 'Halloween',
    recommendedProductId: 'keepsake-mug',
    asset: {
      id: 'asset-here-for-the-boos',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/here-for-the-boos.webp',
      productionUrl: '/designs/fall-2026/here-for-the-boos.png',
      alt: 'Here for the Boos playful ghost and potion cocktail design',
      width: 1275,
      height: 1155,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-little-pumpkin',
    title: 'Little Pumpkin',
    description:
      'Storybook botanical wreath framing our sweetest harvest baby pumpkin with sunflowers and oak leaves.',
    collection: 'Halloween',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-little-pumpkin',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/little-pumpkin.webp',
      productionUrl: '/designs/fall-2026/little-pumpkin.png',
      alt: 'Little Pumpkin storybook botanical autumn harvest wreath',
      width: 5400,
      height: 7200,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-autumn-state-of-mind',
    title: 'Autumn State of Mind',
    description:
      'Elegant golden maple foliage and refined botanical script celebrating the crisp warmth of fall.',
    collection: 'Fall',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-autumn-state-of-mind',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/autumn-state-of-mind.webp',
      productionUrl: '/designs/fall-2026/autumn-state-of-mind.png',
      alt: 'Autumn State of Mind maple foliage and elegant botanical lettering',
      width: 5400,
      height: 7200,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-powered-by-pumpkin-spice',
    title: 'Powered by Pumpkin Spice',
    description:
      'Hand-lettered coffeehouse emblem with towering whipped cream, cinnamon sticks, and fall warmth.',
    collection: 'Fall',
    recommendedProductId: 'keepsake-mug',
    asset: {
      id: 'asset-powered-by-pumpkin-spice',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/powered-by-pumpkin-spice.webp',
      productionUrl: '/designs/fall-2026/powered-by-pumpkin-spice.png',
      alt: 'Powered by Pumpkin Spice coffee cup with whipped cream and cinnamon',
      width: 1275,
      height: 1155,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-sweater-weather',
    title: 'Sweater Weather',
    description:
      'Hygge-inspired circular cable-knit ring framing warm winter mittens and cozy autumn script.',
    collection: 'Fall',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-sweater-weather',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/sweater-weather.webp',
      productionUrl: '/designs/fall-2026/sweater-weather.png',
      alt: 'Sweater Weather cable-knit texture and cozy autumn mittens',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-feast-mode',
    title: 'Feast Mode',
    description:
      'Championship athletic block lettering and savory roasted feast illustration for Thanksgiving champions.',
    collection: 'Thanksgiving',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-feast-mode',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/feast-mode.webp',
      productionUrl: '/designs/fall-2026/feast-mode.png',
      alt: 'Feast Mode bold athletic Thanksgiving roast turkey and banner design',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-thankful-grateful-caffeinated',
    title: 'Thankful, Grateful, Caffeinated',
    description:
      'Farmhouse gratitude typography and steaming morning mug framed with golden wheat stalks.',
    collection: 'Thanksgiving',
    recommendedProductId: 'keepsake-mug',
    asset: {
      id: 'asset-thankful-grateful-caffeinated',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/thankful-grateful-caffeinated.webp',
      productionUrl: '/designs/fall-2026/thankful-grateful-caffeinated.png',
      alt: 'Thankful Grateful Caffeinated typography and morning coffee mug design',
      width: 1275,
      height: 1155,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-thanksgiving-social-club',
    title: 'Thanksgiving Social Club',
    description:
      'Heritage country club crest with overflowing cornucopia horn, wheat sheaves, and harvest motto.',
    collection: 'Thanksgiving',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-thanksgiving-social-club',
      version: 'fall-2026-v1',
      url: '/designs/fall-2026/thanksgiving-social-club.webp',
      productionUrl: '/designs/fall-2026/thanksgiving-social-club.png',
      alt: 'Thanksgiving Social Club heritage crest with harvest cornucopia',
      width: 5400,
      height: 7200,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-haunted-household',
    title: 'The Haunted Household',
    description:
      'A charming custom Halloween family and pet design featuring friendly ghosts, glowing jack-o-lanterns, and personalized household names.',
    collection: 'Halloween',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-haunted-household',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/haunted-household.webp',
      productionUrl: '/designs/seasonal-edit/haunted-household.png',
      alt: 'The Haunted Household retro Halloween family and pet graphic',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-library-of-lost-hours',
    title: 'Library of Lost Hours',
    description:
      'An antique library checkout card for midnight readers, featuring vintage catalog stamps, gothic literature details, and custom reader name.',
    collection: 'Halloween',
    recommendedProductId: 'keepsake-mug',
    asset: {
      id: 'asset-library-of-lost-hours',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/library-of-lost-hours.webp',
      productionUrl: '/designs/seasonal-edit/library-of-lost-hours.png',
      alt: 'Library of Lost Hours antique library checkout card',
      width: 1275,
      height: 1155,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-midnight-hayride',
    title: 'Midnight Hayride Social Club',
    description:
      'A retro Western spectral illustration combining country-music iconography, haunted hayride banners, and optional custom chapter or city.',
    collection: 'Halloween',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-midnight-hayride',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/midnight-hayride.webp',
      productionUrl: '/designs/seasonal-edit/midnight-hayride.png',
      alt: 'Midnight Hayride Social Club retro Western cowboy ghost illustration',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-night-garden-society',
    title: 'Night Garden Society',
    description:
      'An elegant, dark-romantic fall composition featuring an intricate luna moth, night-blooming botanicals, and celestial gold foil detailing.',
    collection: 'Fall',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-night-garden-society',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/night-garden-society.webp',
      productionUrl: '/designs/seasonal-edit/night-garden-society.png',
      alt: 'Night Garden Society elegant botanical and luna moth artwork',
      width: 5400,
      height: 7200,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-field-notes-after-dark',
    title: 'Field Notes After Dark',
    description:
      'An authentic autumn naturalist study with hand-drawn woodland wildlife, specimen classification numbers, and customizable observation location.',
    collection: 'Fall',
    recommendedProductId: 'gallery-poster',
    asset: {
      id: 'asset-field-notes-after-dark',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/field-notes-after-dark.webp',
      productionUrl: '/designs/seasonal-edit/field-notes-after-dark.png',
      alt: 'Field Notes After Dark naturalist autumn woodland study plate',
      width: 5400,
      height: 7200,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
  {
    id: 'design-leftovers-league',
    title: 'The Annual Leftovers League',
    description:
      'An original Thanksgiving group-apparel design celebrating post-feast champions with customizable family name, year, and member roles.',
    collection: 'Thanksgiving',
    recommendedProductId: 'everyday-tee',
    asset: {
      id: 'asset-leftovers-league',
      version: 'seasonal-2026-v1',
      url: '/designs/seasonal-edit/leftovers-league.webp',
      productionUrl: '/designs/seasonal-edit/leftovers-league.png',
      alt: 'The Annual Leftovers League athletic Thanksgiving championship crest',
      width: 3951,
      height: 4800,
      mimeType: 'image/png',
      hasTransparency: true,
    },
  },
];

export const merchProducts: MerchProduct[] = [
  {
    id: 'gallery-poster',
    name: 'Gallery Poster',
    description: 'Archival matte paper with a clean, borderless presentation.',
    kind: 'flat',
    printifyBlueprintId: 282,
    previewTemplateId: 'poster-studio-v1',
    provider: {
      id: 'fixture-poster-provider',
      printifyProviderId: 1,
      name: 'Sprint 1 fixture provider',
      decorationMethods: ['sublimation'],
    },
    variants: [
      {
        id: 'poster-12x18',
        printifyVariantId: 1001,
        title: '12 × 18 in',
        color: 'Paper white',
        size: '12 × 18 in',
        unitPrice: 2900,
        currency: 'USD',
        available: true,
        placeholders: [
          {
            position: 'front',
            decorationMethod: 'sublimation',
            width: 3600,
            height: 5100,
          },
        ],
      },
      {
        id: 'poster-18x24',
        printifyVariantId: 1002,
        title: '18 × 24 in',
        color: 'Paper white',
        size: '18 × 24 in',
        unitPrice: 3900,
        currency: 'USD',
        available: true,
        placeholders: [
          {
            position: 'front',
            decorationMethod: 'sublimation',
            width: 3600,
            height: 4800,
          },
        ],
      },
    ],
    defaultPlacement: {
      position: 'front',
      decorationMethod: 'sublimation',
      normalizedX: 0.5,
      normalizedY: 0.5,
      normalizedScale: 1,
      angle: 0,
      fit: 'contain',
    },
  },
  {
    id: 'everyday-tee',
    name: 'Everyday Tee',
    description: 'Soft cotton jersey with a centered front print.',
    kind: 'apparel',
    printifyBlueprintId: 12,
    previewTemplateId: 'tee-studio-v1',
    provider: {
      id: 'fixture-tee-provider',
      printifyProviderId: 39,
      name: 'Sprint 1 fixture provider',
      decorationMethods: ['dtg'],
    },
    variants: [
      {
        id: 'tee-white-m',
        printifyVariantId: 9576,
        title: 'White / M',
        color: 'White',
        size: 'M',
        unitPrice: 3400,
        currency: 'USD',
        available: true,
        placeholders: [
          {
            position: 'front',
            decorationMethod: 'dtg',
            width: 4500,
            height: 5700,
          },
        ],
      },
      {
        id: 'tee-white-l',
        printifyVariantId: 9577,
        title: 'White / L',
        color: 'White',
        size: 'L',
        unitPrice: 3400,
        currency: 'USD',
        available: true,
        placeholders: [
          {
            position: 'front',
            decorationMethod: 'dtg',
            width: 4500,
            height: 5700,
          },
        ],
      },
    ],
    defaultPlacement: {
      position: 'front',
      decorationMethod: 'dtg',
      normalizedX: 0.5,
      normalizedY: 0.5,
      normalizedScale: 0.82,
      angle: 0,
      fit: 'contain',
    },
  },
  {
    id: 'keepsake-mug',
    name: 'Keepsake Mug',
    description: 'Glossy 11 oz ceramic with a handle-safe two-sided print area.',
    kind: 'drinkware',
    printifyBlueprintId: 68,
    previewTemplateId: 'mug-11oz-v1',
    provider: {
      id: 'fixture-mug-provider',
      printifyProviderId: 99,
      name: 'Sprint 1 fixture provider',
      decorationMethods: ['sublimation'],
    },
    variants: [
      {
        id: 'mug-white-11oz',
        printifyVariantId: 721,
        title: 'White / 11 oz',
        color: 'White',
        size: '11 oz',
        unitPrice: 1900,
        currency: 'USD',
        available: true,
        placeholders: [
          {
            position: 'front',
            decorationMethod: 'sublimation',
            width: 1275,
            height: 1155,
          },
          {
            position: 'back',
            decorationMethod: 'sublimation',
            width: 1275,
            height: 1155,
          },
        ],
      },
    ],
    defaultPlacement: {
      position: 'front',
      decorationMethod: 'sublimation',
      normalizedX: 0.5,
      normalizedY: 0.5,
      normalizedScale: 0.8,
      angle: 0,
      fit: 'contain',
    },
  },
];

export function getMerchProduct(productId: string) {
  const product = merchProducts.find((candidate) => candidate.id === productId);
  if (!product) throw new Error(`Unknown product: ${productId}`);
  return product;
}

export function getCuratedDesign(designId: string) {
  const design = curatedDesigns.find((candidate) => candidate.id === designId);
  if (!design) throw new Error(`Unknown design: ${designId}`);
  return design;
}
