'use client';

import { motion } from 'framer-motion';
import { Container } from '@/components/Container';
import { STYLE_PRESET_SAMPLES } from '@/lib/assets';

export function StylePresets() {
  return (
    <section className="py-24 bg-white relative">
      <Container size="lg">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="inline-block text-xs font-semibold tracking-widest text-indigo-600 uppercase mb-3">
            12 AI Style Presets
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4 tracking-tight">
            One subject,{' '}
            <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
              twelve looks
            </span>
          </h2>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Same puppy, twelve different AI styles. Your photo will work the same way.
          </p>
        </motion.div>

        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {STYLE_PRESET_SAMPLES.map((style, i) => (
            <motion.div
              key={style.slug}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-30px' }}
              transition={{ delay: i * 0.04 }}
              whileHover={{ y: -4 }}
              className="group cursor-pointer"
            >
              <div className="relative aspect-[5/6] rounded-xl overflow-hidden shadow-md hover:shadow-2xl transition-shadow duration-300">
                {/* Skeleton gradient — visible while AI sample loads */}
                <div
                  className={`absolute inset-0 bg-gradient-to-br ${style.gradient}`}
                />

                {/* AI-generated style sample */}
                <img
                  src={style.sample}
                  alt={`${style.name} style sample`}
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                  loading="lazy"
                />

                {/* Bottom gradient overlay for text legibility */}
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/85 via-slate-900/30 to-transparent" />

                {/* Shimmer on hover */}
                <motion.div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/15 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000 pointer-events-none" />

                {/* Caption pinned to bottom */}
                <div className="relative h-full flex flex-col justify-end p-4">
                  <div className="text-white">
                    <p className="text-[10px] tracking-widest uppercase opacity-80 mb-1">
                      {style.tagline}
                    </p>
                    <h3 className="font-bold text-lg leading-tight drop-shadow-md">
                      {style.name}
                    </h3>
                  </div>
                </div>

                {/* Hover arrow indicator */}
                <motion.div
                  initial={{ opacity: 0, y: -4 }}
                  whileHover={{ opacity: 1, y: 0 }}
                  className="absolute top-3 right-3 w-8 h-8 rounded-full bg-white/20 backdrop-blur-md flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <svg
                    className="w-4 h-4 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2.5}
                      d="M17 8l4 4m0 0l-4 4m4-4H3"
                    />
                  </svg>
                </motion.div>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4 }}
          className="text-center text-sm text-slate-500 mt-10"
        >
          Each sample was generated by the same AI engine you&apos;ll use on your photo.
        </motion.p>
      </Container>
    </section>
  );
}
